### PR TITLE
Format code and update subtrees

### PR DESCRIPTION
**Pull request by ilyaraz**

### CODE REVIEW

**Comment by ludwigschmidt** [comment]
Cool, thanks for updating the formatting!

In the future, it might be good to keep the update-subtree commits separate from the commits on our own code. Then it's more clear what changed and in case we need to do a git bisect at some point it will be easier to track down where a error comes from. But I don't think it's worth re-basing this commit.

**Comment by ludwigschmidt** [comment]
The formatting was done with the clang tool you mentioned in the other issue, right? In some places it seems to do something a bit funny, e.g., line 644 in src/test/polytope_hash_test.cc :

https://github.com/FALCONN-LIB/FALCONN/pull/53/files#diff-78

I'm not sure if this is what we want. But if the tool does something sensible in most other cases, it's probably good to use it.

**Comment by ilyaraz** [comment]
It's the only tool for C++ that uses a real parser rather than just using a bunch of ad hoc regular expressions, so we should stick to it.

If you can tweak it so that you are more happy with the results, we can use these settings by default.

**Comment by ludwigschmidt** [comment]
OK, sounds good. I like that the tool is actually a parser, it should be more robust than cpplint.py, which I used a while ago (but I don't remember any big issues actually).

**Pull request merged**
