### PR TITLE
Small fixes to make things work

### PR DESCRIPTION
**Pull request by ilyaraz**

### CODE REVIEW

**Comment by ludwigschmidt** [comment]
Just out of curiosity: does the random benchmark not compile without -pthread for you? On Mac I didn't need that flag. We should probably keep track of these differences somewhere so we remember them when we refactor the Makefile.

**Comment by ilyaraz** [comment]
It does not. BTW, one related comment: I think with `-pthread` compilation takes waaay more time. Not quite sure why.

**Comment by ilyaraz** [comment]
It does not compile without `-pthread` on towhee.

**Comment by ludwigschmidt** [comment]
OK, I updated #14 .

**Pull request merged**
