### PR TITLE
thin Python wrapper to simplify things a bit

### PR DESCRIPTION
**Pull request by ilyaraz**
Needs to be done here:
- rewrite the benchmark to the new version of the package
- write tests for the new wrapper (at least, to make sure that all the functions work)
- add docstrings

### CODE REVIEW

**Comment by ludwigschmidt** [comment]
Looks good, I like that the wrapper can now use named parameters on the Python side. Just one small comment: should we rename `is_dense=False` to `is_sufficiently_dense` (like on the C++ side) or even `is_sufficiently random`? Currently the Python wrapper only supports dense vectors, so people might be confused why their dense vector is not dense by default. `is_sufficiently_dense` would make it consistent with the C++ side, which is good. But `is_sufficiently_random` might be best because it avoids the word "dense" altogether, which should avoid confusion with the distinction between sparse and dense data types. I'd be in favor of changing the C++ code to `is_sufficiently_random` (or just `sufficiently_random`), too.

**Comment by ilyaraz** [comment]
Renamed in 1d89d914274eed0217b6f8b0cc775cc4a28bd801. BTW, one more question. Currently, `_check_query` is pretty strict: it checks if a query is a proper numpy array (and is not say a list of floats). I think it's reasonable, since we care about performance, but I would see arguments against it.

**Comment by ludwigschmidt** [comment]
I think it's good with the check. I'm not actually sure if you could pass a list of floats without the swig wrapper giving you an error.

**Comment by ilyaraz** [comment]
Turns out you can. It also checks the `dtype` properly btw, but it's still good to have an early check, IMO.

**Comment by ludwigschmidt** [comment]
OK, good to know. I still vote for leaving the check in for performance reasons as you suggested. Also, creating a temporary np.array is very easy on the user side, so I don't see a big disadvantage.

And yes, I agree that early checks with easy to read error messages are good.

**Pull request merged**
